version: "3.8"

services:
  app:
    image: greenpeace_mercadopago_coupon:production
    container_name: greenpeace_mercadopago_coupon_production
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    # volumes:
    #   - ./:/home/app/coupon/
    #   - /home/app/coupon/node_modules/
    # expose:
    #   - '3000'
    # ports:
    #   - '3000:3000'
    # environment:
    #   - PORT=3000
    # command: npm run client:start:production
