version: "3.8"

services:
  coupon:
    image: greenpeace_mercadopago_coupon:dev
    container_name: greenpeace_mercadopago_coupon
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./:/home/app/coupon/
      - /home/app/coupon/node_modules/
    expose:
      - '3001'
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
    command: npm run client:start:development
    stdin_open: true
